<?php
/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) 2000-2015 LOCKON CO.,LTD. All Rights Reserved.
 *
 * http://www.lockon.co.jp/
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */


namespace Eccube\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * CrudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrudRepository extends EntityRepository
{
    /**
     * getAllDataSortByUpdateDate
     * dtb_crudの値を全て返却、引数により更新日をソート
     *
     * @param string $order
     * @return array|bool
     */
    public function getAllDataSortByUpdateDate($order = 'asc')
    {
        $qb = $this->createQueryBuilder('dc');

        $qb->select('dc')
            ->orderBy('dc.update_date', $order);

        $res = $qb->getQuery()->getResult();

        return count($res) > 0 ? $res : false;
    }

    /**
     * getDataById
     * dtb_crudの値をIDで引き当て、返却
     *
     * @param string $order
     * @return array|bool
     */
    public function getDataById($id = null)
    {
        if (is_null($id)) {
            return false;
        }

        try {
            $qb = $this->createQueryBuilder('dc');
            $qb->select('dc')
                ->where('dc.id = :Id')
                ->setParameter('Id', $id);

            return $qb->getQuery()->getSingleResult();
        } catch(\NoResultException $e) {
            return false;
        }
    }

    /**
     * save
     *
     * @param \Eccube\Entity\Crud $entity
     * @return bool
     */
    public function save(\Eccube\Entity\Crud $entity)
    {
        $em = $this->getEntityManager();

        try {
            $em->beginTransaction();
            $em->persist($entity);
            $em->flush($entity);
            $em->commit();
        } catch (\Exception $e) {
            $em->rollback();

            return false;
        }

        return true;
    }

}
