<?php

namespace Plugin\GiftWrapping\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WrappingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WrappingRepository extends EntityRepository
{
}