<?php
namespace Plugin\LikeNiko\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NikoInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NikoInfoRepository extends EntityRepository
{
    /**
     * @param  \Plugin\LikeNiko\Entity\NikoInfo $NikoInfo
     * @return bool
     */
    public function save(\Plugin\LikeNiko\Entity\NikoInfo $NikoInfo)
    {
        $em = $this->getEntityManager();
        $em->getConnection()->beginTransaction();
        try {

            $em->persist($NikoInfo);
            $em->flush();

            $em->getConnection()->commit();
        } catch (\Exception $e) {
            $em->getConnection()->rollback();

            return false;
        }

        return true;
    }
}
